version: '2'
catalog:
  name: "Graylog"
  version: "0"
  description: "Open source log management that actually works. Pour le port 9000, veuillez passer par un nouveau LoadBalancer si vous voulez le rendre public. Attention : cette version n'est pas entierement fonctionnelle"
  questions:
    - variable: graylog_password
      description: "Password in sha2"
      label: "SHA2 Password"
      type: "string"
      required: true
      default: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    - variable: graylog_secret
      description: "Password secret"
      label: "Password secret"
      type: "string"
      required: true
      default: "somepasswordpepper"
    - variable: graylog_fqdn
      description: "address of graylog https/http"
      label: "FQDN"
      type: "string"
      required: true
      default: "http://graylog.example.com:9000"
  logstash-config:
    metadata:
      logstash: &id001
        inputs: |+
          udp {
            port => 5000
            codec => "json"
          }
        outputs: |+
          gelf {
            host => "graylog"
            port => "12201"
          }
    scale: 1
  logstash:
    metadata:
      logstash: *id001
    scale: 1