version: '2'
volumes:
  graylog-elasticsearch-storage-volume:
    driver: local
  graylog-mongodb:
    driver: local
  graylog-journal:
    driver: local

services:

  elasticsearch-storage:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '1000'
      SERVICE_UID: '1000'
      SERVICE_VOLUME: /usr/share/elasticsearch/data
    volumes:
    - graylog-elasticsearch-storage-volume:/usr/share/elasticsearch/data
    labels:
      io.rancher.container.start_once: 'true'

  elasticsearch-sysctl:
    image: rawmind/alpine-sysctl:0.1
    privileged: true
    environment:
    - "SYSCTL_KEY=vm.max_map_count"
    - "SYSCTL_VALUE=262144"
    labels:
      io.rancher.container.start_once: 'true'

  elasticsearch:
    mem_limit: 1073741824
    cap_add:
    - IPC_LOCK
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: 'true'
      cluster.name: elasticsearch-cluster-log
      discovery.zen.minimum_master_nodes: '1'
      discovery.zen.ping.unicast.hosts: elasticsearch
      node.data: 'true'
      node.master: 'true'
      node.name: $${HOSTNAME}
      xpack.security.enabled: 'false'
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        hard: 262144
        soft: 262144
    volumes_from:
    - elasticsearch-storage
    labels:
      io.rancher.sidekicks: elasticsearch-storage, elasticsearch-sysctl
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: facing=db
  
  # configured to grab docker logs from
  # /var/run/docker.sock on host machine
  # and forward them to logstash
  # which is a separate service available
  # over the network.
  logspout:
    image: bekt/logspout-logstash:master
    restart: on-failure
    environment:
      ROUTE_URIS: "logstash+tcp://logstash:9514"
      LOGSPOUT: 'ignore'
      LOGSTASH_TAGS: "docker,ec2"
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    tty: true
    stdin_open: true
    depends_on:
    - logstash
    labels:
      io.rancher.scheduler.global: true
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  logstash:
    image: avvo/logstash:latest
    environment:
      - xpack.monitoring.enable: false
      - LOGSPOUT: ignore
      - FEATURE_ELASTICSEARCH: false
      - FEATURE_GELF: true
      - FEATURE_STDOUT: false
      - FEATURE_HARDWAREPORT: false
      - GELF_HOST: graylog
      - GELF_PORT: 12201
    ports:
      - 8514:8514/tcp
      - 8514:8514/udp
      - 9514:9514/tcp
      - 9514:9514/udp
      - 5000:5000/tcp
    labels:
      io.rancher.scheduler.global: true
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      logspout.exclude: true

  mongodb:
    image: mongo:3
    volumes:
      - graylog-mongodb:/data/db
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: facing=db

  graylog:
    image: throrin19/graylog-plugins:2.3.1-1
    volumes:
      - graylog-journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: ${graylog_secret}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${graylog_password}
      GRAYLOG_WEB_ENDPOINT_URI: ${graylog_fqdn}/api
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "false"
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: facing=frontend