version: '2'
catalog:
  name: "Graylog"
  version: "0"
  description: "logging stack for ec2 environments"
  questions:
    - variable: graylog_password
      description: "Password in sha2"
      label: "SHA2 Password"
      type: "string"
      required: true
      default: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    - variable: graylog_secret
      description: "Password secret"
      label: "Password secret"
      type: "string"
      required: true
      default: "somepasswordpepper"
    - variable: graylog_external_endpoint
      description: external hostname your browser will connect to for graylog
      label: "Graylog External Address"
      type: "string"
      required: true