name: Avvo Logging
description: This stack manages log routing, collection, indexing, and viewing.
version: 0
category: "Core Infrastructure"
license: Private
maintainer: Infrastructure Team
projectURL: https://github.com/avvo/rancher-catalog