version: '2'
services:
  logstash-lb: # temp until we integrate w/current lb setup
    image: rancher/lb-service-haproxy:latest
    ports:
    - 5000
  logstash:
    image: avvo/logstash:latest # point to latest for testing and a tagged release for others
    stdin_open: true
    tty: true
    ports:
    - 5000:5000/tcp
    labels:
      io.rancher.container.hostname_override: container_name