version: '2'
catalog:
  name: "LogStash config testing"
  version: "0"
  description: "for configuring and testing logstash in stag"
services:
  logstash-lb:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 5000
        target_port: 5000
        protocol: tcp
        service: logstash
    health_check:
      port: 5000
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000